language: node_js

node_js:
  - 0.10
  - 0.12
  - 4.2

sudo: false

branches:
  only:
    - master

env:
  matrix:
    - NPM_3=true
    - NPM_3=false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - 'if [ "$NPM_3" = true ]; then npm install -g npm@3; else true; fi'

script:
  - npm run check-ci
  - ls  coverage/server/lcov.info | cat
  - cat coverage/server/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"